sudo: required
language: node_js
node_js:
  - "8.11.2"

services:
  - mongodb

before_install:
  - curl https://install.meteor.com | /bin/sh
  - export PATH="$HOME/.meteor:$PATH"

before_script:
  - meteor npm install

script:
  - meteor build --server-only ../new_package && mv ../new_package/*.tar.gz package.tar.gz

cache:
  directories:
    - node_modules

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master